### ISSUE TITLE
Proposal: using Poetry 

### ISSUE THREAD

**Issue by TiansuYu** [irgeek/StrEnum#32]
How about using Poetry to manage dependencies? Also potentially could use tox to test against different python versions.

**Comment by TiansuYu** [comment]
Also, consider using pre-commit hooks on this.

**Comment by irgeek** [comment]
The library is already tested against multiple Python versions as part of the GitHub Actions workflow.

As for Poetry, I don't see what the benefit would be. The fact it lets you lock your dependency versions can be useful when managing whole applications, but this is a pretty low-level library with _zero_ runtime dependencies. Convince me otherwise. :)

And as far as pre-commit hooks go--what do you think I should be using them for?

**Comment by stumpylog** [comment]
[hatch](https://hatch.pypa.io/latest/) might be a better choice, as it doesn't do the locking, etc, which is more for an application, not a library.

Some quick benefits would be:
- Replacing 5 files with just pyproject.toml
- [`hatch version`](https://hatch.pypa.io/latest/version/) is easy to manage the version
